### ISSUE TITLE
todayFocus causing script error

### ISSUE THREAD

**Issue by cobbenterprises** [702573N/Obsidian-Tasks-Timeline#29]
When I have my query as:

```dataviewjs
await dv.view("taskido", {
pages: ""
options: "todayFocus"

})
```

I get this error:

Evaluation Error: SyntaxError: Unexpected identifier
    at DataviewInlineApi.eval (plugin:dataview:19673:21)
    at evalInContext (plugin:dataview:19674:7)
    at asyncEvalInContext (plugin:dataview:19681:16)
    at DataviewJSRenderer.render (plugin:dataview:19705:19)
    at DataviewJSRenderer.onload (plugin:dataview:19289:14)
    at DataviewJSRenderer.e.load (app://obsidian.md/app.js:1:864580)
    at t.e.addChild (app://obsidian.md/app.js:1:864981)
    at t.addChild (app://obsidian.md/app.js:1:1417524)
    at Object.addChild (app://obsidian.md/app.js:1:1416549)
    at DataviewApi.executeJs (plugin:dataview:20214:19)

**Comment by 702573N** [comment]
Hi,
each parameter must be separated with a comma, unfortunately you forgot one:

````
```dataviewjs
await dv.view("taskido", {
pages: "",
options: "todayFocus"
})
```
````
